# Generated by Django 2.1.7 on 2019-05-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_auto_20190514_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'завяка на обратный звонок', 'verbose_name_plural': 'заявки на обратный звонок'},
        ),
        migrations.AddField(
            model_name='callback',
            name='processed',
            field=models.BooleanField(default=False, help_text='Да, если уже перезвонили', verbose_name='Обработана'),
        ),
    ]
