# Generated by Django 2.1.7 on 2019-05-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190511_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousel',
            field=models.BooleanField(default=False, verbose_name='Отображать в карусели'),
        ),
    ]
