# Generated by Django 2.1.7 on 2019-05-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.FileField(default='', upload_to='images/', verbose_name='Изображение 1(Большое'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img1_mini',
            field=models.FileField(default='', upload_to='images/', verbose_name='Изображение 1(миниатюра)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.FileField(default='', upload_to='images/', verbose_name='Изображение 2(большое)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img2_mini',
            field=models.FileField(default='', upload_to='images/', verbose_name='Изображение 2(миниатюра)'),
            preserve_default=False,
        ),
    ]
