# Generated by Django 2.1.7 on 2019-05-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190514_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img1_mini',
            new_name='img_mini',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2_mini',
        ),
    ]
