# Generated by Django 2.1.7 on 2019-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_descriptionparagraph_fat_minerals_otheringredient_vitamins'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='amount',
            field=models.CharField(default='', max_length=50, verbose_name='На 100гр.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fat',
            name='name',
            field=models.CharField(default='', max_length=75, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minerals',
            name='amount',
            field=models.CharField(default='', max_length=50, verbose_name='На 100гр.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minerals',
            name='name',
            field=models.CharField(default='', max_length=75, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otheringredient',
            name='amount',
            field=models.CharField(default='', max_length=50, verbose_name='На 100гр.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otheringredient',
            name='name',
            field=models.CharField(default='', max_length=75, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamins',
            name='amount',
            field=models.CharField(default='', max_length=50, verbose_name='На 100гр.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamins',
            name='name',
            field=models.CharField(default='', max_length=75, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
