# Generated by Django 2.1.7 on 2019-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190515_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='product_advantages')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fat',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='minerals',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='otheringredient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='vitamins',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='minerals',
            name='chemistry_name',
            field=models.CharField(default='', max_length=20, verbose_name='Химическое название'),
            preserve_default=False,
        ),
    ]
