# Generated by Django 2.1.7 on 2019-05-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190516_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='descriptionparagraph',
            name='body',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descriptionparagraph',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='descriptionparagraph',
            name='description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', related_query_name='paragraphs', to='catalog.ProductDescription'),
            preserve_default=False,
        ),
    ]
