# Generated by Django 2.1.7 on 2019-05-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190516_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beauty_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product3', to='catalog.ProductDescription', verbose_name='Текст о красоте'),
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product2', to='catalog.ProductDescription', verbose_name='Текст о кулинарии'),
        ),
        migrations.AddField(
            model_name='product',
            name='health_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='catalog.ProductDescription', verbose_name='Текст о здоровье'),
        ),
    ]
