# Generated by Django 2.1.7 on 2019-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190516_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionparagraph',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='descriptionparagraph',
            name='position',
            field=models.IntegerField(blank=True, help_text='Влияет на порядок вывода текста', null=True, unique=True, verbose_name='Порядковый номер порядка'),
        ),
    ]
