# Generated by Django 2.1.7 on 2019-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190516_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionparagraph',
            name='position',
            field=models.IntegerField(blank=True, help_text='Влияет на порядок вывода текста', null=True, verbose_name='Порядковый номер порядка'),
        ),
    ]
