# Generated by Django 2.1.7 on 2019-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190516_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadvantages',
            name='text',
            field=models.CharField(default='', max_length=150, verbose_name='Описание преимущества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productadvantages',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Название преимущества'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productadvantages',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='product_advantages/', verbose_name='Иконка'),
        ),
    ]
