# Generated by Django 2.1.7 on 2019-05-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190516_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAdvantages',
            new_name='ProductAdvantage',
        ),
    ]
