# Generated by Django 2.1.7 on 2019-05-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190516_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название')),
                ('type', models.CharField(choices=[('v', 'Витамины'), ('m', 'Минералы'), ('f', 'Жиры'), ('o', 'Остальное')], max_length=20, verbose_name='Тип')),
                ('amount', models.CharField(max_length=50, verbose_name='На 100гр.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='fat',
            name='product',
        ),
        migrations.RemoveField(
            model_name='minerals',
            name='product',
        ),
        migrations.RemoveField(
            model_name='otheringredient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vitamins',
            name='product',
        ),
        migrations.DeleteModel(
            name='Fat',
        ),
        migrations.DeleteModel(
            name='Minerals',
        ),
        migrations.DeleteModel(
            name='OtherIngredient',
        ),
        migrations.DeleteModel(
            name='Vitamins',
        ),
    ]
