# Generated by Django 2.1.7 on 2019-05-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190521_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionparagraph',
            options={'ordering': ('position',), 'verbose_name': 'параграф', 'verbose_name_plural': 'параграфы'},
        ),
        migrations.AlterModelOptions(
            name='productdescription',
            options={'verbose_name': 'описание продукта', 'verbose_name_plural': 'описания продукта'},
        ),
    ]
