# Generated by Django 2.1.7 on 2019-05-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190521_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingrs_file',
            field=models.FileField(default='', upload_to='ingredients/', verbose_name='Файл таблицы ингредиентов'),
            preserve_default=False,
        ),
    ]
