# Generated by Django 2.2.1 on 2020-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20190522_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productadvantage',
            options={'verbose_name': 'преимущества покупки', 'verbose_name_plural': 'преимущества покупки'},
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отображается'),
        ),
    ]
