# Generated by Django 2.2.1 on 2021-03-18 09:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200723_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='beauty_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cooking_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='health_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingrs_file',
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cosmetology_description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='health_description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DescriptionParagraph',
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
