# Generated by Django 2.2.1 on 2021-03-18 14:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20210318_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cooking_image',
            field=models.ImageField(default=None, null=True, upload_to='product_description/'),
        ),
        migrations.AddField(
            model_name='product',
            name='cosmetology_image',
            field=models.ImageField(default=None, null=True, upload_to='product_description/'),
        ),
        migrations.AddField(
            model_name='product',
            name='health_image',
            field=models.ImageField(default=None, null=True, upload_to='product_description/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cooking_description',
            field=tinymce.models.HTMLField(verbose_name='Текст о использовании в готовке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cosmetology_description',
            field=tinymce.models.HTMLField(verbose_name='Текст о косметологии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='health_description',
            field=tinymce.models.HTMLField(verbose_name='Текст о здоровье'),
        ),
    ]
