# Generated by Django 2.2.1 on 2021-03-18 14:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20210318_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cooking_description',
            field=tinymce.models.HTMLField(default='', verbose_name='Текст о использовании в готовке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cosmetology_description',
            field=tinymce.models.HTMLField(default='', verbose_name='Текст о косметологии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='health_description',
            field=tinymce.models.HTMLField(default='', verbose_name='Текст о здоровье'),
        ),
    ]
