# Generated by Django 2.1.7 on 2019-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, unique=True, verbose_name='Позиция')),
                ('img', models.FileField(upload_to='banners/', verbose_name='Изображение')),
                ('img_alt', models.CharField(help_text='Короткое описание изображения', max_length=150, verbose_name='Alt текст')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
                'ordering': ('position',),
            },
        ),
    ]
