# Generated by Django 2.1.7 on 2019-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_indexpagesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpagesettings',
            options={'verbose_name': 'настройки главной страницы', 'verbose_name_plural': 'настройки главной страницы'},
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='banner_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст баннера'),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='h1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок баннера(h1)'),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
