# Generated by Django 2.1.7 on 2019-05-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190514_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagesettings',
            name='logo',
        ),
    ]
