# Generated by Django 2.1.7 on 2019-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_indexpageadvantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_aboutus_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название блока о компании'),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_advantages_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название блока приемущества'),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_products_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название блока карусель товаров'),
        ),
    ]
