# Generated by Django 2.1.7 on 2019-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190514_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_aboutus_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание блока о компании'),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_advantages_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание блока приемущества'),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_products_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание блока карусель товаров'),
        ),
    ]
