# Generated by Django 2.1.7 on 2019-05-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_indexpagetestimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_test_background',
            field=models.FileField(default='', upload_to='test/', verbose_name='Фон блока'),
            preserve_default=False,
        ),
    ]
