# Generated by Django 2.1.7 on 2019-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20190520_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_aboutus_video',
            field=models.FileField(default='', upload_to='about_us/', verbose_name='Видео блока о компании'),
            preserve_default=False,
        ),
    ]
