# Generated by Django 2.1.7 on 2019-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_indexpagesettings_block_aboutus_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagesettings',
            name='block_aboutus_video',
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='block_aboutus_background',
            field=models.FileField(default='', upload_to='about_us/', verbose_name='Задний фон блока о компании'),
            preserve_default=False,
        ),
    ]
