# Generated by Django 2.1.7 on 2019-05-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20190521_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpageadvantages',
            name='icon',
            field=models.FileField(upload_to='advantages', verbose_name='Изображение'),
        ),
    ]
