# Generated by Django 2.1.7 on 2019-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190514_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Электронная почта организации'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_email',
            field=models.CharField(blank=True, help_text='Почта для оповещений с сайта', max_length=50, null=True, verbose_name='Электронная почта сайта'),
        ),
    ]
