# Generated by Django 2.1.7 on 2019-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190514_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(default='', verbose_name='Текст о нас'),
            preserve_default=False,
        ),
    ]
