# Generated by Django 2.1.7 on 2019-05-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190514_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us',
        ),
    ]
