# Generated by Django 2.1.7 on 2019-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190521_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='font1',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='Шрифт 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font2',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='Шрифт 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font3',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='Шрифт 3'),
        ),
    ]
