# Generated by Django 2.1.7 on 2019-05-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190521_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='font1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='font2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='font3',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_additional',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='Шрифт дополнительных текстов'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_block_header',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='Шрифт заголовка блоков'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_page_header',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='Шрифт заголовка страницы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_product_header',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='Шрифт заголовка товаров'),
        ),
    ]
