# Generated by Django 2.2.1 on 2020-07-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_buttons_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Общие настройки сайта', 'verbose_name_plural': 'Общие настройки сайта'},
        ),
    ]
